const productsArray = [
    {
        id: 1,
        name: 'iPhone X',
        description: 'This is iPhone X',
        type: 'phone',
        capacity: 64,
        price: 500,
        image: '/images/iphone_14pro.jpg',
    },
    {
        id: 2,
        name: 'iPhone XS',
        description: 'This is iPhone XS',
        type: 'phone',
        capacity: 128,
        price: 700,
        image: '/images/iphone_13mini.jpg',
    },
    {
        id: 3,
        name: 'iPhone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 256,
        price: 1200,
        image: '/images/iphone_13pro.jpg',
    },
    {
        id: 4,
        name: 'iPhone 12Pro',
        description: 'This is iPhone 12Pro',
        type: 'phone',
        capacity: 128,
        price: 850,
        image: '/images/iphone_11.jpg',
    },
    {
        id: 5,
        name: 'iPhone 5S',
        description: 'This is iPhone 5S',
        type: 'phone',
        capacity: 32,
        price: 200,
        image: '/images/iphone_11mini.jpg',
    },
    {
        id: 6,
        name: 'iPhone 3G',
        description: 'This is iPhone 3G',
        type: 'phone',
        capacity: 16,
        price: 250,
        image: '/images/iphone_se.jpg',
    },
]

export default productsArray
